---
title: "Resume"
---

Education
=========

- **[İstanbul Teknik Üniversitesi (İTÜ)](https://www.itu.edu.tr/en/homepage)**

  *Ph.D., [Earth Science](https://eies.itu.edu.tr/en/home), under M. Sinan Özeren's supervision*       *November 2018*

- **[Muğla Üniversitesi](https://www.mu.edu.tr/en)**     Muğla, Türkiye
      
  *MS, [Geology](http://jeoloji.mu.edu.tr/en)*             *June, 2013*


- **[Boğaziçi Üniversitesi](http://boun.edu.tr/en-US/Index)**     İstanbul, Türkiye
  
  *B.S., [Maths](http://www.math.boun.edu.tr/)*                        *June, 2009*


Academic Experience
===================

- ***Muğla SK Üniversitesi***             
    *Lecturer*                     (*January, 2019 -- Present*)

    -   Statistics and probability

    -   Introduction to computing and programming for earth scientists

    -   Computer applications in geological engineering

-  ***Muğla Üniversitesi***               
      *Research Assistant*           (*February, 2015 -- December, 2018*)

    -   Statistics and probability

    -   Introduction to programming

    -   Historical geology and paleontology

    -   Marine geology

    -   Field geology

    -   Introduction to paleoclimate

    -   Quaternary environmental change

    -   Paleoclimatology

    -   Holocene climate variability at western Anatolia, comparison
        with Middle East and Europe

    -   Paleoceanography

- ***İTÜ***                          
      *Research Assistant*           (*September, 2013 -- February, 2015*)
      
- ***Muğla Üniversitesi***                          
      *Research Assistant*           (*February, 2012 -- September, 2013*)
      
Research Interests
==================

-   Climatology & Paleoclimatology

-   Statistical methods

-   Applications of information theoretical methods

-   Stochastic processes

-   Bayesian statistics

Research Projects
=================

1.  Ancient and Future Forests. 2022--2023, **Researcher**, supported by
    British Council in Ankara. Project Coordinators: Alan M. Greaves &
    Sena Akçer-Ön.

2.  Sakarya Nehri güncel taşkın ovası örneğinde akarsu çökellerinin
    geçmiş hidrolojik ekstremler (HEX) açısından olay stratigrafisinin
    çoklu-vekil yaklaşımı ile belirlenme potansiyelinin araştırılması.
    2021--2022, **Researcher**, supported by TÜBİTAK (The Scientific and
    Technological Research Council of Turkey). Project Coordinator:
    M. Korhan Erturaç.

3.  Late Holocene Climate Changes and it's Relation with Solar Forcing
    in Southwestern Anatolia from Lake Gölcük (Isparta) Sediment
    Records. 2018--2019, **Researcher**, supported by TÜBİTAK (The
    Scientific and Technological Research Council of Turkey). Project
    Coordinator: Sena Akçer-Ön.

4.  Palaeoclimate of Southwestern Anatolia during the Quaternary Period:
    Lake Acıgöl and Lake Salda sediment records. 2015--2017,
    **Researcher**, supported by TÜBİTAK (The Scientific and
    Technological Research Council of Turkey). Project Coordinator: Sena
    Akçer-Ön.

5.  High Resolution Climate and Environment Studies from Sediment and
    Water Samples of Lake Salda (Burdur). 2015--2017, **Researcher**,
    supported by Muğla Üniversitesi. Project Coordinator: Sena Akçer-Ön.