---
title: "Papers"
---

Articles
====================================


-   Danladi, IB, Akçer-Ön, S, Litt, T, **Ön, ZB**, Wacker, L 2023. A
    Late Holocene Climate Reconstruction from the High-Altitude Lake
    Gölcük Sedimentary Records, Isparta (SW Anatolia), *Quaternary
    Research*. [doi:
    10.1017/qua.2023.26](https://drive.google.com/file/d/14xeKAg-hkIamHicQGcqJirJJ9D6W9Ipx/view?usp=sharing)

-   **Ön, ZB**. Dates of Holocene environmental changes in Lake Bafa: A
    hierarchical Bayesian analysis of change points, *Turkish
    Geographical Reviews* 82, 23--36. [doi:
    10.17211/tcd.1283443](https://drive.google.com/file/d/1r85I8WGSidOwtrQDL6cqUXAVFzhldPkW/view?usp=sharing)

-   **Ön, ZB** 2023. A Bayesian change point analysis re-examines the
    4.2 ka BP event in southeast Europe and southwest Asia, *Quaternary
    Science Reviews*, 312 (108163). [doi:
    10.1016/j.quascirev.2023.108163](https://drive.google.com/file/d/1vL5QfG3pCY6CXeYtoMXvoeJAp6PmGwB0/view?usp=sharing)

-   **Ön, ZB**, Macdonald, N, Akçer-Ön, S and Greaves AM 2023. A novel
    Bayesian multilevel regression approach to the reconstruction of an
    eastern Mediterranean temperature record for the last 10,000 years.
    *The Holocene* 33(7), 807--815. [doi:
    10.1177/09596836231163508](https://drive.google.com/file/d/1NG-VHwcqLf6HcY2KQTWaT261aaqpMg4o/view?usp=sharing)


-   Danladi, IB, Akçer-Ön, S, **Ön, ZB** and Schmidt, S. High-resolution
    temperature and precipitation variability of southwest Anatolia
    since 1730 CE from Lake Gölcük sedimentary records, *Turkish Journal
    of Earth Sciences* 30, 601--610. [doi:
    10.3906/yer-2008-14](https://drive.google.com/file/d/1LDgVlst3zDm92xACUASXtI5STT1TeLNm/view?usp=sharing)

6.  **Ön, ZB**, Greaves, AM, Akçer-Ön, S and Özeren, MS 2021. A Bayesian
    test for the 4.2 ka BP abrupt climatic change event in southeast
    Europe and southwest Asia using structural time series analysis of
    paleoclimate data, *Climatic Change* 165, 7. [doi:
    10.1007/s10584-021-03010-6](https://drive.google.com/file/d/1ivgaBEc3Aj_uSg9wwNJKpRwhnzgOQg9k/view?usp=sharing)


-   Akçer-Ön, S, Greaves, AM, Manning, SW, **Ön, ZB**, Çağatay, MN,
    Sakınç, M, Oflaz, A, Tunoğlu, C and Salihoğlu R 2020. Redating the
    formation of Lake Bafa, western Turkey: Integrative
    geoarchaeological methods and new environmental and dating evidence,
    *Geoarchaeology* 35, 659--677. [doi:
    10.1002/gea.21791](https://drive.google.com/file/d/1R3zNV1FGaZ50a9icUUuMy5keqX7FsOi7/view?usp=sharing)


-   **Ön, ZB** and Özeren, MS 2018. Temperature and precipitation
    variability in eastern Anatolia: Results from independent component
    analysis of Lake Van sediment data spanning the last 250 kyr ,
    *Quaternary International* 514, 119--129. [doi:
    10.1016/j.quaint.2018.11.037](https://drive.google.com/open?id=1bxLS6Y5CE1W5Be1SRzLN4F1ILCG66lAJ)


-   Eriş, KK, Akçer-Ön, S, Çağatay, MN, Ülgen, UB, **Ön, ZB**, Gürocak,
    Z, Nagihan Arslan, T, Akkoca, DB, Damcı, E, İnceöz, M, Okan,
    ÖÖ 2017. Late Pleistocene to Holocene paleoenvironmental evolution
    of Lake Hazar, Eastern Anatolia, Turkey, *Quaternary International*
    486, 4--16. [doi:
    10.1016/j.quaint.2017.09.027](https://drive.google.com/open?id=1oM-UrQsnAQ3-zoPjSKquZjT5XGX0eaPu)

-   **Ön, ZB**, Akçer-Ön, S, Özeren, MS, Eriş, KK, Greaves, AM and
    Çağatay, MN 2017. Climate proxies for the last 17.3 ka from Lake
    Hazar (Eastern Anatolia), extracted by independent component
    analysis of $\mu$-XRF data, *Quaternary International* 486, 17--28.
    [doi:
    10.1016/j.quaint.2017.08.066](https://drive.google.com/open?id=1M8RUCkGVO8cjqqhcW-mH1W-df2P--ozi)

-   **Ön, ZB**, Özeren, MS, Akçer-Ön, S and Çağatay, MN 2017. Spectral
    Features of 250 kyr BP Long Lake Van Sediments: Milankovitch Cycles
    and Their Harmonics, *Geological Bulletin of Turkey* 60, 1--28.
    [doi:
    10.25288/tjb.360604](https://drive.google.com/open?id=1Jzyn2Vk6YMeowki-20hRgm8z34fZXjbs)


-   Kaiser, J, **Ön, ZB**, Arz, HW and Akçer-Ön, S 2016. Sedimentary
    lipid biomarkers in the magnesium rich and highly alkaline Lake
    Salda (south-western Anatolia), *Journal of Limnology*, 75,
    581--596. [doi:
    10.4081/jlimnol.2016.1337](https://drive.google.com/open?id=1HTA1TV5aU9byflGqBR5TWeBpzPwZxkUU)
    
Comments, Replies & Popular Articles
====================================

-   **Ön, ZB**, Greaves, AM and Akçer-Ön, S, Özeren, MS 2019. Comment
    on H. Weiss' review of "Is there evidence for a 4.2 ka B.P. event in
    the northern North Atlantic region?", *Climate of the Past
    Discussions*. [doi:
    10.5194/cp-2018-162-SC2](https://drive.google.com/open?id=1lBAknkBdg5la-pa4xen9k_uqFIDbQExs)

-   **Ön, ZB** 2017. How X-Ray Fluorescence Methods Reveal Past Climate
    Changes.
    <https://sciencetrends.com/x-ray-fluorescence-methods-reveal-past-climate-changes/>